# Generated by Django 2.2.4 on 2019-08-08 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Contact number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banknote_person_created_by', related_query_name='banknote_person_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banknote_person_updated_by', related_query_name='banknote_person_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('updated_on', 'created_on'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('id_num', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('series', models.CharField(blank=True, max_length=50)),
                ('serial_number', models.CharField(blank=True, max_length=50)),
                ('grading', models.CharField(blank=True, max_length=50)),
                ('inferred', models.CharField(blank=True, max_length=50)),
                ('denomination', models.CharField(blank=True, max_length=50)),
                ('variety', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True, max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to='uploads/')),
                ('appraiser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banknote_appraisal_created_by', related_query_name='banknote_appraisal_created_by', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banknote.Person')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banknote_appraisal_updated_by', related_query_name='banknote_appraisal_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('updated_on', 'created_on'),
                'abstract': False,
            },
        ),
    ]
