# Generated by Django 2.1.4 on 2018-12-11 14:00

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True, verbose_name='Contact number'),
        ),
    ]
